from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path

# Load the stylesheet once when this module is imported
_STYLE_PATH = Path(__file__).parent / "stylesheet.qss"

with open(_STYLE_PATH, "r", encoding="utf-8") as f:
    STYLEsheet = f.read()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 770)
        MainWindow.setStyleSheet(STYLEsheet)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_root = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_root.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_root.setSpacing(0)
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 78))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 78))
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_header.setContentsMargins(16, -1, 24, -1)
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.logoLabel = QtWidgets.QLabel(self.headerFrame)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_header.addWidget(self.logoLabel)
        self.groupLabel = QtWidgets.QLabel(self.headerFrame)
        self.groupLabel.setStyleSheet("font-size:28px;font-weight:bold;")
        self.groupLabel.setObjectName("groupLabel")
        self.horizontalLayout_header.addWidget(self.groupLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.headerFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_header.addWidget(self.titleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem1)
        self.verticalLayout_root.addWidget(self.headerFrame)
        self.bodyFrame = QtWidgets.QFrame(self.centralwidget)
        self.bodyFrame.setObjectName("bodyFrame")
        self.horizontalLayout_body = QtWidgets.QHBoxLayout(self.bodyFrame)
        self.horizontalLayout_body.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_body.setSpacing(0)
        self.horizontalLayout_body.setObjectName("horizontalLayout_body")
        self.sidebarFrame = QtWidgets.QFrame(self.bodyFrame)
        self.sidebarFrame.setMinimumSize(QtCore.QSize(230, 0))
        self.sidebarFrame.setMaximumSize(QtCore.QSize(230, 16777215))
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.verticalLayout_sidebar.setContentsMargins(18, 24, 18, 24)
        self.verticalLayout_sidebar.setSpacing(10)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.menuTitle = QtWidgets.QLabel(self.sidebarFrame)
        self.menuTitle.setObjectName("menuTitle")
        self.verticalLayout_sidebar.addWidget(self.menuTitle)
        self.btnRFC = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnRFC.setCheckable(True)
        self.btnRFC.setChecked(True)
        self.btnRFC.setObjectName("btnRFC")
        self.verticalLayout_sidebar.addWidget(self.btnRFC)
        self.btnAngle = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnAngle.setCheckable(True)
        self.btnAngle.setObjectName("btnAngle")
        self.verticalLayout_sidebar.addWidget(self.btnAngle)
        self.btnParticles = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnParticles.setCheckable(True)
        self.btnParticles.setObjectName("btnParticles")
        self.verticalLayout_sidebar.addWidget(self.btnParticles)
        self.line1 = QtWidgets.QFrame(self.sidebarFrame)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.verticalLayout_sidebar.addWidget(self.line1)
        self.connectionTitle = QtWidgets.QLabel(self.sidebarFrame)
        self.connectionTitle.setObjectName("connectionTitle")
        self.verticalLayout_sidebar.addWidget(self.connectionTitle)
        self.serialPortLabel = QtWidgets.QLabel(self.sidebarFrame)
        self.serialPortLabel.setObjectName("serialPortLabel")
        self.verticalLayout_sidebar.addWidget(self.serialPortLabel)
        self.horizontalLayout_serialPort = QtWidgets.QHBoxLayout()
        self.horizontalLayout_serialPort.setObjectName("horizontalLayout_serialPort")
        self.comboSerialPort = QtWidgets.QComboBox(self.sidebarFrame)
        self.comboSerialPort.setObjectName("comboSerialPort")
        self.comboSerialPort.addItem("")
        self.comboSerialPort.addItem("")
        self.comboSerialPort.addItem("")
        self.horizontalLayout_serialPort.addWidget(self.comboSerialPort)
        self.btnRefreshPorts = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnRefreshPorts.setObjectName("btnRefreshPorts")
        self.horizontalLayout_serialPort.addWidget(self.btnRefreshPorts)
        self.verticalLayout_sidebar.addLayout(self.horizontalLayout_serialPort)
        self.baudLabel = QtWidgets.QLabel(self.sidebarFrame)
        self.baudLabel.setObjectName("baudLabel")
        self.verticalLayout_sidebar.addWidget(self.baudLabel)
        self.lineBaudrate = QtWidgets.QLineEdit(self.sidebarFrame)
        self.lineBaudrate.setObjectName("lineBaudrate")
        self.verticalLayout_sidebar.addWidget(self.lineBaudrate)
        self.btnConnect = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnConnect.setObjectName("btnConnect")
        self.verticalLayout_sidebar.addWidget(self.btnConnect)
        self.line2 = QtWidgets.QFrame(self.sidebarFrame)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setObjectName("line2")
        self.verticalLayout_sidebar.addWidget(self.line2)
        self.controlTitle = QtWidgets.QLabel(self.sidebarFrame)
        self.controlTitle.setObjectName("controlTitle")
        self.verticalLayout_sidebar.addWidget(self.controlTitle)
        self.btnStart = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout_sidebar.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(self.sidebarFrame)
        self.btnStop.setEnabled(False)
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout_sidebar.addWidget(self.btnStop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sidebar.addItem(spacerItem2)
        self.horizontalLayout_body.addWidget(self.sidebarFrame)
        self.mainFrame = QtWidgets.QFrame(self.bodyFrame)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_main.setContentsMargins(22, 24, 22, 24)
        self.verticalLayout_main.setSpacing(20)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(14)
        self.cardsLayout.setObjectName("cardsLayout")
        self.cardVeloc = QtWidgets.QFrame(self.mainFrame)
        self.cardVeloc.setStyleSheet("QLabel#cardTitle1{font-size:13px;font-weight:bold;} QLabel#cardNumber1{font-size:26px;font-weight:bold;}")
        self.cardVeloc.setObjectName("cardVeloc")
        self.cardLayout1 = QtWidgets.QVBoxLayout(self.cardVeloc)
        self.cardLayout1.setObjectName("cardLayout1")
        self.Veloc_label = QtWidgets.QLabel(self.cardVeloc)
        self.Veloc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Veloc_label.setObjectName("Veloc_label")
        self.cardLayout1.addWidget(self.Veloc_label, 0, QtCore.Qt.AlignTop)
        self.Veloc_value = QtWidgets.QDoubleSpinBox(self.cardVeloc)
        self.Veloc_value.setObjectName("Veloc_value")
        self.cardLayout1.addWidget(self.Veloc_value, 0, QtCore.Qt.AlignHCenter)
        self.Veloc_unit = QtWidgets.QLabel(self.cardVeloc)
        self.Veloc_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.Veloc_unit.setObjectName("Veloc_unit")
        self.cardLayout1.addWidget(self.Veloc_unit)
        self.cardsLayout.addWidget(self.cardVeloc)
        self.cardAcc = QtWidgets.QFrame(self.mainFrame)
        self.cardAcc.setObjectName("cardAcc")
        self.cardLayout2 = QtWidgets.QVBoxLayout(self.cardAcc)
        self.cardLayout2.setObjectName("cardLayout2")
        self.Acc_label = QtWidgets.QLabel(self.cardAcc)
        self.Acc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Acc_label.setObjectName("Acc_label")
        self.cardLayout2.addWidget(self.Acc_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Acc_value = QtWidgets.QDoubleSpinBox(self.cardAcc)
        self.Acc_value.setObjectName("Acc_value")
        self.cardLayout2.addWidget(self.Acc_value, 0, QtCore.Qt.AlignHCenter)
        self.Acc_unit = QtWidgets.QLabel(self.cardAcc)
        self.Acc_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.Acc_unit.setObjectName("Acc_unit")
        self.cardLayout2.addWidget(self.Acc_unit)
        self.cardsLayout.addWidget(self.cardAcc)
        self.cardAng = QtWidgets.QFrame(self.mainFrame)
        self.cardAng.setObjectName("cardAng")
        self.cardLayout3 = QtWidgets.QVBoxLayout(self.cardAng)
        self.cardLayout3.setObjectName("cardLayout3")
        self.Ang_label = QtWidgets.QLabel(self.cardAng)
        self.Ang_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Ang_label.setObjectName("Ang_label")
        self.cardLayout3.addWidget(self.Ang_label, 0, QtCore.Qt.AlignTop)
        self.Ang_value = QtWidgets.QDoubleSpinBox(self.cardAng)
        self.Ang_value.setObjectName("Ang_value")
        self.cardLayout3.addWidget(self.Ang_value, 0, QtCore.Qt.AlignHCenter)
        self.Ang_unit = QtWidgets.QLabel(self.cardAng)
        self.Ang_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.Ang_unit.setObjectName("Ang_unit")
        self.cardLayout3.addWidget(self.Ang_unit)
        self.cardsLayout.addWidget(self.cardAng)
        self.cardDTime = QtWidgets.QFrame(self.mainFrame)
        self.cardDTime.setObjectName("cardDTime")
        self.cardLayoutTime = QtWidgets.QVBoxLayout(self.cardDTime)
        self.cardLayoutTime.setObjectName("cardLayoutTime")
        self.DTime_label = QtWidgets.QLabel(self.cardDTime)
        self.DTime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.DTime_label.setObjectName("DTime_label")
        self.cardLayoutTime.addWidget(self.DTime_label, 0, QtCore.Qt.AlignTop)
        self.DTime_value = QtWidgets.QDoubleSpinBox(self.cardDTime)
        self.DTime_value.setObjectName("DTime_value")
        self.cardLayoutTime.addWidget(self.DTime_value, 0, QtCore.Qt.AlignHCenter)
        self.DTime_unit = QtWidgets.QLabel(self.cardDTime)
        self.DTime_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.DTime_unit.setObjectName("DTime_unit")
        self.cardLayoutTime.addWidget(self.DTime_unit)
        self.cardsLayout.addWidget(self.cardDTime)
        self.cardReps = QtWidgets.QFrame(self.mainFrame)
        self.cardReps.setObjectName("cardReps")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardReps)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Reps_label = QtWidgets.QLabel(self.cardReps)
        self.Reps_label.setObjectName("Reps_label")
        self.verticalLayout.addWidget(self.Reps_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Reps_value = QtWidgets.QDoubleSpinBox(self.cardReps)
        self.Reps_value.setObjectName("Reps_value")
        self.verticalLayout.addWidget(self.Reps_value, 0, QtCore.Qt.AlignHCenter)
        self.Reps_unit = QtWidgets.QLabel(self.cardReps)
        self.Reps_unit.setText("")
        self.Reps_unit.setObjectName("Reps_unit")
        self.verticalLayout.addWidget(self.Reps_unit)
        self.cardsLayout.addWidget(self.cardReps)
        self.verticalLayout_main.addLayout(self.cardsLayout)
        self.consoleFrame = QtWidgets.QFrame(self.mainFrame)
        self.consoleFrame.setMinimumSize(QtCore.QSize(0, 150))
        self.consoleFrame.setObjectName("consoleFrame")
        self.verticalLayout_console = QtWidgets.QVBoxLayout(self.consoleFrame)
        self.verticalLayout_console.setObjectName("verticalLayout_console")
        self.plainConsole = QtWidgets.QPlainTextEdit(self.consoleFrame)
        self.plainConsole.setEnabled(False)
        self.plainConsole.setReadOnly(True)
        self.plainConsole.setObjectName("plainConsole")
        self.verticalLayout_console.addWidget(self.plainConsole)
        self.verticalLayout_main.addWidget(self.consoleFrame)
        self.horizontalLayout_body.addWidget(self.mainFrame)
        self.verticalLayout_root.addWidget(self.bodyFrame)
        self.footerFrame = QtWidgets.QFrame(self.centralwidget)
        self.footerFrame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.footerFrame.setObjectName("footerFrame")
        self.horizontalLayout_footer = QtWidgets.QHBoxLayout(self.footerFrame)
        self.horizontalLayout_footer.setObjectName("horizontalLayout_footer")
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_footer.addItem(spacerItem3)
        self.statusLabel = QtWidgets.QLabel(self.footerFrame)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_footer.addWidget(self.statusLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_footer.addItem(spacerItem4)
        self.readyLabel = QtWidgets.QLabel(self.footerFrame)
        self.readyLabel.setObjectName("readyLabel")
        self.horizontalLayout_footer.addWidget(self.readyLabel)
        self.verticalLayout_root.addWidget(self.footerFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RFC Control Panel"))
        self.logoLabel.setText(_translate("MainWindow", "RFC"))
        self.groupLabel.setText(_translate("MainWindow", "StepperMotor"))
        self.titleLabel.setText(_translate("MainWindow", " CONTROL PANEL"))
        self.menuTitle.setText(_translate("MainWindow", "TEST SELECTION"))
        self.btnRFC.setText(_translate("MainWindow", "  ∿   RFC"))
        self.btnAngle.setText(_translate("MainWindow", "  ∠   ANGLE"))
        self.btnParticles.setText(_translate("MainWindow", "  ◌   PARTICLES"))
        self.connectionTitle.setText(_translate("MainWindow", "COM CONNECTION"))
        self.serialPortLabel.setText(_translate("MainWindow", "Serial Port"))
        self.comboSerialPort.setItemText(0, _translate("MainWindow", "COM3"))
        self.comboSerialPort.setItemText(1, _translate("MainWindow", "COM4"))
        self.comboSerialPort.setItemText(2, _translate("MainWindow", "COM5"))
        self.btnRefreshPorts.setToolTip(_translate("MainWindow", "Refresh COM ports"))
        self.btnRefreshPorts.setText(_translate("MainWindow", "↻ refresh"))
        self.baudLabel.setText(_translate("MainWindow", "Baud rate"))
        self.lineBaudrate.setText(_translate("MainWindow", "115200"))
        self.btnConnect.setText(_translate("MainWindow", "⛓  CONNECT"))
        self.controlTitle.setText(_translate("MainWindow", "CONTROL"))
        self.btnStart.setText(_translate("MainWindow", "▷  START"))
        self.btnStop.setText(_translate("MainWindow", "■  STOP"))
        self.Veloc_label.setText(_translate("MainWindow", " Velocity"))
        self.Veloc_unit.setText(_translate("MainWindow", "RPM"))
        self.Acc_label.setText(_translate("MainWindow", "Acceleration"))
        self.Acc_unit.setText(_translate("MainWindow", "RPM/s"))
        self.Ang_label.setText(_translate("MainWindow", "Angle"))
        self.Ang_unit.setText(_translate("MainWindow", "Degree"))
        self.DTime_label.setText(_translate("MainWindow", "Delay Time"))
        self.DTime_unit.setText(_translate("MainWindow", "Seconds"))
        self.Reps_label.setText(_translate("MainWindow", "Repetition"))
        self.plainConsole.setPlaceholderText(_translate("MainWindow", "> LOG / OUTPUT CONSOLE"))
        self.statusLabel.setText(_translate("MainWindow", "●  STATUS: DISCONNECTED"))
        self.readyLabel.setText(_translate("MainWindow", "READY."))
